version: '3.8'

services:
  blockscout-stats:
    image: ghcr.io/blockscout/stats:${STATS_DOCKER_TAG:-latest}
    pull_policy: always
    platform: linux/amd64
    restart: always
    container_name: 'blockscout-stats'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file:
      -  ../envs/common-stats.env
    environment:
      - STATS__DB_URL=postgres://blockscout:ceWb1MeLBEeOIfk65gU8EjF8@blockscout-db:5432/stats
      - STATS__BLOCKSCOUT_DB_URL=postgresql://blockscout:ceWb1MeLBEeOIfk65gU8EjF8@blockscout-db:5432/blockscout?ssl=false
      - STATS__CREATE_DATABASE=true
      - STATS__RUN_MIGRATIONS=true
